# services to enable
[grpc.services.gateway]
datagateway = "https://sciencemesh.softwaremind.com/iop/datagateway"
commit_share_to_storage_grant = true
commit_share_to_storage_ref = true

[grpc.services.storageregistry]
[grpc.services.storageregistry.drivers.static]
home_provider = "/home"

[grpc.services.storageregistry.drivers.static.rules]
"/home" = "iop-storageprovider-home:17000"
"/reva" = "iop-storageprovider-reva:18000"
"123e4567-e89b-12d3-a456-426655440000" = "iop-storageprovider-reva:18000"

[grpc.services.storageprovider]
data_server_url = "https://sciencemesh.softwaremind.com/iop/data"
[grpc.services.authprovider]
[grpc.services.authregistry]
[grpc.services.userprovider]
[grpc.services.usershareprovider]
[grpc.services.publicshareprovider]
[grpc.services.ocmcore]
[grpc.services.ocmshareprovider]
[grpc.services.ocminvitemanager]
[grpc.services.ocmproviderauthorizer]

[http.services.datagateway]
[http.services.dataprovider]
[http.services.prometheus]
[http.services.ocmd]

[http.services.ocmd.smtp_credentials]
sender_mail = "sciencemesh@service.ailleron.com"
sender_password = "A#&vBJ5p!c"
smtp_server = "service.ailleron.com"
smtp_port = 25
