apiVersion: v1
kind: Service
metadata:
  name: reva-standalone-svc
spec:
  type: NodePort
  ports:
  - name: gateway
    port: 19000
    nodePort: 32090
  - name: datagateway
    port: 19001
    nodePort: 32091
  selector:
    app.kubernetes.io/instance: reva-standalone

